version: '3.9'
services:
    back:
        build:
            context: .
            dockerfile: /docker/dockerfile
        networks:
            - back
        volumes:
            - ./:/app
        ports:
            - "8000:8000"
        working_dir: /app

    postgres:
        image: postgres:alpine
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        networks:
            - back
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - bd:/var/lib/postgresql

volumes:
    bd:
networks:
    back:

