version: '3.9'
services:
  back:
    build:
      context: .
      dockerfile: /docker/dockerfile
    ports:
      - "8080:8000"
    working_dir: /app

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - bd:/var/lib/postgresql

volumes:
  bd: