version: '3.9'

volumes:
    bd:

networks:
    back:

services:
    api:
        build:
            context: .
            dockerfile: /docker/dockerfile
            target: php
        networks:
            - back
        ports:
            - "8000:8000"
        working_dir: /app
        depends_on:
            - postgres
        volumes:
            - ./:/app

    schedule:
        build:
            context: .
            dockerfile: /docker/dockerfile
            target: cron
        depends_on:
            - postgres
        networks:
            - back

    postgres:
        image: postgres:alpine
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        networks:
            - back
        ports:
            - "5432:5432"
        volumes:
            - bd:/var/lib/postgresql

