FROM php:8.2-cli

WORKDIR /app

RUN apt-get update \
    # Минимальные утилиты
    && apt-get install -y zip unzip mc bash\
    # Модули для php-ext
    libxml2-dev libpq-dev \
    # php extension
    && docker-php-ext-install pdo pdo_pgsql pgsql \
    bcmath

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
COPY ./ /app

RUN composer install --no-dev

EXPOSE 8000

CMD php artisan serve --host=0.0.0.0 --port=8000
